import io
import zipfile
from datetime import datetime


def build_website_zip(project_content: dict) -> bytes:
    """
    Builds an in-memory ZIP containing index.html, style.css, and README.txt
    from the project_content dict generated by the website tool.
    Returns raw bytes suitable for a StreamingResponse.
    """
    business_name = project_content.get("business_name", "My Business")
    html_content = project_content.get("html", "")
    css_content = project_content.get("css", _default_css(project_content))
    tagline = project_content.get("tagline", "")

    readme = f"""# {business_name} Website
Generated by The Brand Factory NOLA
Date: {datetime.utcnow().strftime("%Y-%m-%d")}

## Files
- index.html  — Main landing page
- style.css   — Stylesheet (already linked from index.html)
- README.txt  — This file

## Getting Started
1. Open index.html in your browser to preview locally.
2. Upload all files to your web host or deploy via Netlify/Vercel.

Tagline: {tagline}

---
Built with The Brand Factory NOLA — https://brandfactorynola.com
"""

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("index.html", html_content)
        zf.writestr("style.css", css_content)
        zf.writestr("README.txt", readme)

    buf.seek(0)
    return buf.read()


def _default_css(project_content: dict) -> str:
    color = project_content.get("primary_color", "#c9a84c")
    return f"""/* Brand Factory NOLA — Generated Stylesheet */
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
    font-family: 'Segoe UI', system-ui, sans-serif;
    background: #0d0d0d;
    color: #f5f0e8;
    line-height: 1.6;
}}
a {{ color: {color}; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
header {{
    background: #111;
    border-bottom: 2px solid {color};
    padding: 1.5rem 2rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
}}
header h1 {{ color: {color}; font-size: 1.8rem; letter-spacing: 1px; }}
.hero {{
    text-align: center;
    padding: 6rem 2rem;
    background: linear-gradient(135deg, #111 0%, #1a1a1a 100%);
}}
.hero h2 {{ font-size: 3rem; color: {color}; margin-bottom: 1rem; }}
.hero p {{ font-size: 1.2rem; max-width: 600px; margin: 0 auto 2rem; }}
.btn {{
    display: inline-block;
    padding: 0.8rem 2rem;
    background: {color};
    color: #0d0d0d;
    font-weight: 700;
    border-radius: 4px;
    transition: opacity 0.2s;
}}
.btn:hover {{ opacity: 0.85; text-decoration: none; }}
section {{ padding: 4rem 2rem; max-width: 900px; margin: 0 auto; }}
footer {{
    text-align: center;
    padding: 2rem;
    background: #111;
    color: #666;
    font-size: 0.85rem;
    border-top: 1px solid #222;
}}
"""
